security:
    ignored: /**

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/invoices?useSSL=false
        username: root
        password: toor
    jpa:
        hibernate:
            ddl-auto: create
        generate-ddl: true
#    jooq:
#        sql-dialect: org.hibernate.dialect.MySQL8Dialect
#hikari.maximumPoolSize= 10
#hikari.pool-name= hikariPool
#hikari.register-mbeans= true
